- blockchain/utreexoviewpoint.go
- wire/udata.go
- wire/udata_test.go
There exists an edge case where the leaf data count will not match the
batchproof target count.  When the leaf being deleted is a root, there
will not be any proof.  However, we still need to provide the leaf data
for that root for utxo validation (validation of the signature, amount,
etc).
The new serialization for both the compact and normal udata will include
a varint serialized count of the leaf data before the actual leaf data.
The check for targets and leaf data count equality in the function
ProofSanity() is now removed as there is no guarantee that they will be
equal.
> wire/udata: Explicitly serialize the leaf data count.

- blockchain/common.go
- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- blockchain/indexers/utreexoproofindex.go
- blockchain/utreexoviewpoint.go
ProveUtxos() method is defined for the utreexo proof indexes.  Given
arbitrary utxos, it will provide a proof for them with respect to the
current UTXO set state at the chaintip.
> blockchain, indexers: Add support for proving arbitrary UTXOs with Utreexo proof indexes

- mempool/estimatefee.go
Fixes a negative index bug that makes the node crash on chain
reorganizations.  The bug is detailed in
github.com/btcsuite/btcd/issues/1660.
A better design than just skipping the transaction would make
the fee estimator more accurate and that should implemented
at a later date
[paniclog.log](https://github.com/utreexo/utreexod/files/7760405/paniclog.log)
> mempool/estimatefee: Fix negative index bug

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- blockchain/indexers/utreexoproofindex.go
- blockchain/utreexoviewpoint.go
- blockchain/utreexoviewpoint_test.go
- btcjson/chainsvrcmds.go
- btcjson/chainsvrcmds_test.go
- btcjson/chainsvrresults.go
- rpcserver.go
- rpcserverhelp.go
RPC call proveutxochaintipinclusion now has a verbosity option.  By
default it is on and when on, it will print the json representation of
the proof along with the raw serialized hex string of the entire proof.
When the verbosity is off, the proveutxochaintipinclusion call will only
return the raw serialized hex string of the proof.
> rpcserver: Add verbosity option to proveutxochaintipinclusion

- blockchain/chainio.go
- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- blockchain/indexers/utreexoproofindex.go
- blockchain/utreexoviewpoint.go
- server.go
- wire/udata.go
Implement initial multi-block proof support.  The flatutreexoproofindex
behaves the same as before and the new code is not used during ibd.
There's no guarantee that the multiblockproof is correct.  Currently it
syncs ok but there isn't code where the CSNs use the proof.
> indexers/flatutreexoproofindex: Initial Multi-block proof

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- blockchain/indexers/utreexoproofindex.go
- blockchain/utreexoviewpoint.go
- wire/udata.go
- wire/udata_test.go
TTL field is removed in favor of other caching methods as research has
shown that there are better alternative caching methods than ttl based
caching.
> wire/udata: Remove ttl field from UData

- blockchain/chain.go
- blockchain/utreexoviewpoint.go
- blockchain/validate.go
Functionality that was included in Modify() is now refactored into 3
separate functions: Modify(), IngestProof(), and ExtractAccumulatorAddDels().
Modify now only modifies the accumulator without any other checks.
IngestProof validates and ingests the proof so that the caller can call
Modify().
ExtractAccumulatorAddDels now does the proof sanity checks and extracts
the additions and deletions from the block that was passed in.
> blockchain/utreexoviewpoint: Refactor Modify() function

- .github/workflows/go.yml
- blockchain/indexers/indexers_test.go
- mempool/mempool_test.go
GoLint was not being installed correctly, so it was throwing error code 127 when we were running the workflow. Fixed that issue, so that it is installed correctly.
Also, there were some linting errors that were arising since now an updated golangci-lint is being used.
> go.yml: Fix github workflow and linting errors

- go.mod
- go.sum
The updated utreexo repository supports undoing cached proofs now. Updating it will allow supporting wallets with utreexo proofs.
> go.*: Update utreexo repository

- blockchain/chain.go
- blockchain/utreexoviewpoint.go
- btcjson/chainsvrcmds.go
- btcjson/chainsvrresults.go
- btcutil/block.go
- config.go
- log.go
- rpcserver.go
- rpcserverhelp.go
- server.go
- wallet/log.go
- wallet/watchonly.go
- wire/msgblock.go
The watch only wallet keeps supports registering addresses and xpubs and it keeps track of relevant utxos and the utreexo proof for those utxos.
This allows users running Utreexo compact state nodes to keep track of the proofs for their own utxos, allowing the compact state nodes to prove txs to each other.
The watch only wallet is currently a work in progress ands registering xpubs are not supported yet. However, it can keep track of relevant utxos and the utreexo proof and supports handling reorgs as well.
> Add watchonly wallet

- blockchain/blockindex.go
- blockchain/chain.go
- blockchain/chain_test.go
This PR adds the missing `invalidateblock` rpc call. The call is useful for both manually testing changes with the cli or creating automated tests.
The behavior of Bitcoin Core is mimicked. However, since we currently don't keep track of which block was received first, the prioritization of choosing whichever block is received first for the active chain tip is omitted.
> blockchain: Add invalidateblock method to BlockChain

- integration/invalidate_reconsider_block_test.go
- rpcclient/chain.go
- rpcserver.go
- rpcserverhelp.go
The invalidateblock and reconsiderblock methods on BlockChain are now exposed through rpc. These two functions are useful to have as they make it easier to test things on regtest.
> main, rpcclient: Add rpc for invalidateblock and reconsiderblock

- rpcclient/chain.go
Three added methods: `GetUtreexoProof`, `ProveWatchOnlyChainTipInclusion`, and `VerifyUtxoChainTipClusion` allow for the integration tests to test nodes with utreexo flags turned on.
`GetUtreexoProof` allows for the fetching of the utreexo proof from a `--flatutreexoproofindex` or `--utreexoproofindex` node.
`ProveWatchOnlyChainTipInclusion` allows for fetching the chain tip proof from a node with `--watchonlywallet` flag.
`VerifyUtxoChainTipInclusion` allows for the verification of the fetched chain tip proof.
> rpcclient: Add utreexo calls to rpc clients 

- integration/utreexocompactstatenode_test.go
- wallet/watchonly.go
Bugs that affected reorganizations in the watch only wallet code are fixed and an integration test in added to test the functionality of the watch only wallet.
The integration test not only tests that the watch only wallet bug is fixed but it also tests that the bridge node and the csn is able to sync up and handle reorganizations.
> wallet, integration: Fix watchonlywallet bugs

- blockchain/merkle.go
- blockchain/merkle_test.go
Two merkle tree functions are added. ExtractMerkleBranch let's you extract the merkle proof for a single hash in a merkle tree. HashMerkleRoot provides a function for calculating the merkle root given the hash, position, and the merkle branch.
This commit is part of the effort to add electrum server support to utreexod. Electrum protocol requires serving merkle proofs for a given tx and the extract provides that functionality. HashMerkleRoot is added to test that the returned result from ExtractMerkleBranch is correct.
> blockchain: Add ExtractMerkleBranch and HashMerkleRoot

- config.go
- server.go
No need to have cfilters as a default index. It adds the overhead of computation and disk space for utreexo nodes. # # #
> main: Remove cfilters as a default index

- go.mod
- go.sum
The new utreexo library has fixes for GetProofSubset which is critical for the watch only wallet.
> go.mod, go.sum: Update Utreexo library

- blockchain/utreexoviewpoint.go
VerifyUData now includes the leafhash in the error message.
> blockchain: Better error message for VerifyUData

- netsync/manager.go
A utreexo compact state node requires the utreexo proofs to validate blocks and transactions. Only utreexo nodes are able to provide them so ignore invs from non-utreexo peers.
> netsync: Only take invs from utreexo nodes as a CSN

- btcjson/example_test.go
- btcjson/jsonrpc.go
- btcjson/jsonrpc_test.go
Instead of returning nil for the error field when the error is nil, it is omitted if the error is nil. Having the error field causes error for the electrum protocol as it expects no error fields if the error is nil.
> btcjson: Omit empty error for btcjson.Response

- config.go
- electrum/log.go
- electrum/server.go
- log.go
- server.go
The added electrum server is stateless and all the information it serves
is fetched either from the watchonly wallet or the node's own
mempool/blockchain data.
The server supports electrum protocol version v1.4.1 and is tested to be
fully compatible with the electrum desktop wallet (electrum.org) and the
nunchuk wallet (nunchuk.io). Other wallets should work but were not
tested.
> electrum, main: Add electrum server

- blockchain/utreexoviewpoint.go
Adds a small check that the proof targets we received matches the count of the dels we've extracted from the block.
> blockchain: add assertion check to ProcessUData

- blockchain/chain.go
- blockchain/chain_test.go
- blockchain/chainio.go
- blockchain/chainio_test.go
- blockchain/indexers/indexers_test.go
- blockchain/reorg_test.go
- blockchain/sizehelper.go
- blockchain/sizehelper_test.go
- blockchain/utxocache.go
- blockchain/utxocache_test.go
- blockchain/utxoviewpoint.go
- blockchain/validate.go
- cmd/addblock/import.go
- goclean.sh
- netsync/manager.go
The utxo cache code in the current code is fragile and less performant.
Thus we're replacing it with the better code from btcd.
> blockchain: add utxocache/utxoviewpoint code from btcd

- blockchain/chain.go
- blockchain/chainio.go
- blockchain/chainio_test.go
- blockchain/utreexoviewpoint.go
MapPollard supports a more efficient caching vs stump. This opens up more efficient mempool protocol.
> blockchain: change the utreexoview to mappollard

- chaincfg/params.go
- server.go
DNS seeds allows you to filter addresses by features. This PR asks for utreexo peers (service bit 1 << 24 is set) if `-utreexo` is enabled. This helps to find bridge nodes for the first IBD.
Also add `seed.dlsouza.lol` that supports this feature.
> Use signet seeds to return utreexo nodes

- blockchain/utreexoviewpoint.go
- server.go
- wire/udata.go
The server code that only allowed for bridge nodes to serve blocks/tx to
utreexo nodes is now changed so that a csn that has all the neccessary
data is able to send data to another csn.
> blockchain, wire, main: allow csns to serve utreexo data

- blockchain/utreexoviewpoint.go
- mempool/mempool.go
- server.go
- wallet/watchonly.go
- wire/leaf.go
- wire/leaf_test.go
- wire/udata.go
Adds code so that the proof is cached and then regenerated for receiving and sending txs to utreexo nodes.
> main, mempool, blockchain, wire, wallet:  initial mempool support for partial proofs

- blockchain/bench_test.go
- blockchain/blockindex.go
- blockchain/blockindex_test.go
On startup, Ancestor call was taking a lot of time when the node was loading the blockindex onto memory. This change speeds up the Ancestor function significantly and speeds up the node during startup.
On testnet3 at blockheight ~2,500,000, the startup was around 30seconds on current main and was 5 seconds with this change. Below is a benchstat result showing the significant speedup.
```
goos: darwin
goarch: arm64
pkg: github.com/utreexo/utreexod/blockchain
│     old.txt      │               new.txt                │
│      sec/op      │    sec/op     vs base                │
Ancestor-8   120819.301µ ± 5%   7.013µ ± 19%  -99.99% (p=0.000 n=10)
│  old.txt   │            new.txt             │
│    B/op    │    B/op     vs base            │
Ancestor-8   0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 …
```
> blockchain: better Ancestor with skiplists

- config.go
This increase is so that the utreexo peer isn't punished for performing ibd.
When a utreexo csn node is performing ibd, it is able to sync much faster than a traditional node. This has resulted in cases of where a csn is banned while performing ibd.
> main: increase ban threshold to 300

- chaincfg/chainhash/hash.go
- chaincfg/chainhash/hash_test.go
Packed hashes are just 4 uint64s written into a 32 byte hash. This is mostly done to keep compatibility with existing inv message flow for tx propagation.
> chainhash: add packed hashes support

- wire/invvect.go
- wire/invvect_test.go
Utreexo proof hash invs are always paired with a utreexo tx inv and it's used to communicate which positions of the leaves that are in the accumulator is being spent in the tx.
> wire: add utreexo proof hash inv

- blockchain/utreexoviewpoint.go
This allows the mempool proofs that don't have the entire proof to be validated as well.
> blockchain: call VerifyPartialProof instead of VerifyProof

- blockchain/utreexoviewpoint.go
- wire/udata.go
The added methods in this PR allow for fetching the needed data during partial tx proof propapgation
> blockchain, wire: utreexoviewpoint partial proof support

- peer/peer.go
- peer/peer_test.go
- server.go
For utreexo tx inv messages, the invvects will be related to each other as the invvect for the tx will be matched with the position invs. It'll look like so:
[InvTypeUtreexoTx][TXID1]
[InvTypeProofHash][packed positions1.1] (4 positions) [InvTypeProofHash][packed positions1.2] (1 position)
At the moment the invvects can only be queued one at a time which may result in the InvTypeProofHash to be separated from the InvTypeUtreexoTx. Allowing for queuing multiple invvects eliminates this problem.
> peer, main: allow for queuing multiple invvects

- txscript/standard.go
- txscript/standard_test.go
There was a case on testnet where the witness was empty and resulted in the csn crashing. This will prevent that from happening.
> txscript: add check to see if witness is empty

- electrum/server.go
- mempool/mempool.go
- netsync/manager.go
- peer/peer.go
- rpcserver.go
- server.go
On tx propagation, a utreexo node may not need the entire proof as some may be cached. This new way of propagating txs is based off of https://github.com/utreexo/utreexo/discussions/77 and allows a utreexo node to only ask for the proof hashes it is missing.
> main, netsync, peer: full partial tx support

- .github/workflows/go.yml
- README.md
- blockchain/chainio.go
- config.go
- goclean.sh
- integration/bip0009_test.go
- integration/csv_fork_test.go
- integration/getchaintips_test.go
- integration/invalidate_reconsider_block_test.go
- integration/rpcserver_test.go
- integration/rpctest/rpc_harness_test.go
- integration/utreexocompactstatenode_test.go
- server.go
- utreexod.go
Since users would expect to run csns, when using utreexod, make it the default and have a flag for turning it off.
Some additional checks added in so that it errors on startup when a user tries to switch between a utreexo and a non-utreexo node.
> main, blockchain: make csn the default

- btcutil/bech32/bech32.go
- btcutil/bech32/bech32_test.go
- btcutil/bech32/error.go
- btcutil/bech32/version.go
Porting over taproot changes from btcd.
> btcutil: bech32m

- blockchain/utxoviewpoint.go
For csns, as they don't have the utxo set data, don't try to fetch from it as it'll result in a panic.
> blockchain: prevent panic for utreexo csns

- chaincfg/chainhash/hash.go
- chaincfg/chainhash/hash_test.go
- wire/leaf.go
- wire/leaf_test.go
For versioning purposes, we want to prepend the version info before the
leaf data when generating the hash. Instead of sha256 used in bip340, we
use sha512 as it's benchmarked to perform better for leafdatas.
> chainhash, wire: implement tagged hashes for utreexo leaves

- config.go
Since people expect utreexo nodes to be tiny, make the pruning by default.
> main: make utreexo nodes pruned by default

- blockchain/indexers/addrindex.go
- blockchain/indexers/cfindex.go
- blockchain/indexers/common.go
- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/manager.go
- blockchain/indexers/ttlindex.go
- blockchain/indexers/txindex.go
- blockchain/indexers/utreexoproofindex.go
- server.go
Remove the separate call to setchain and make the chain setting part of the Init() method on the indexers.
> indexers, main: remove setchain for the utreexo proof indexes

- blockchain/utreexoviewpoint.go
- blockchain/validate.go
- blockchain/validate_test.go
Since utreexo leaf hashes have the block hash committed into the
preimage, there's no overwriting of the utxos of the historical bip30
violations. But since non-utreexo nodes consider them unspendable, we
must also state them as unspendable to avoid consensus
incompatibilities.
> blockchain: make utxos that were overwritten by bip30 violations unspendable

- utreexod.go
If the user explicitly sets the GOGC env variable, don't override it.
> main: respect env gogc

- addrmgr/addrmanager_internal_test.go
There's a bug that happens occasionally that I'm pretty sure is
happening because these tests are running in parallel. Give the tmp
directories different paths to fix the bug.
The error is always:
`addrmanager_internal_test.go:165: expected to find 5 adddresses, found 4`
If anything it's ioutil.TmpDir is deprecated so this is a good change.
> addrmgr: fix testing bug that happens here and there

- txscript/pkscript.go
- txscript/standard.go
- txscript/standard_test.go
For p2pkh, there was a script that added arbitrary data with OP_DROP before the actual signature and the pubkey leading to a failure in pkscript reconstruction. Added tests extra tests now that make sure this bug doesn't happen.
> txscript: fix reconstruct bug for p2pkh

- blockchain/utreexoviewpoint.go
- txscript/standard.go
- txscript/standard_test.go
What's considered to be a reconstructable pkscript is now more strict. A p2pkh sigscript may have extra opcodes that may break the assumption that the sigscript will only have two data pushes of the signature and the public key.
We redefine what's reconstructable as the last data push of the sigscript must be the preimage of the pubkey hash or the script hash. Anything that doesn't fit in this model is considered not reconstructable.
> txscript: change to a stricter reconstruct types

- cmd/utreexoctl/config.go
- cmd/utreexoctl/httpclient.go
- config.go
- config_test.go
- rpcserver.go
- sample-utreexod.conf
One pain point with utreexod and utreexoctl was that you have to manually set rpcuser and rpcpassword when you start utreexod in order to use the rpcserver. This cookie fallback allows users to simply start up the node with `utreexod` and have access to the bdkwallet with utreexoctl
> main, utreexoctl: add cookie based login

- blockchain/utreexoio.go
These new types can be used to store the mappollard and enable a bridge node that doesn't load the entire merkle forest onto memory.
> blockchain: add database types that implement mappollard backends

- blockchain/indexers/manager.go
Having the defer forced a utreexo index flush after the index was built. This change makes it so that it only triggers the flush when the program is shutting down.
> indexers: move utreexo index flushing so it only triggers on interrupts

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/utreexobackend.go
- blockchain/indexers/utreexoproofindex.go
- blockchain/utreexoio.go
The utreexo state backend is changed to mappollard and both of the
indexes are changed to be fully on disk instead of on memory.
Fixes #63
> blockchain, indexers: change utreexo bridges to mappollard

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- blockchain/indexers/utreexobackend.go
- blockchain/indexers/utreexoproofindex.go
- blockchain/utreexoio.go
- blockchain/utreexoio_test.go
- config.go
- server.go
Instead of only being on disk, the utreexo bridges now have a default cache of 250mib with it also being configurable. Users can choose to have the entire utreexo tree in memory or on bridge as well.
> blockchain, indexers: Add cache option to bridgenodes

- go.mod
- go.sum
The updated utreexo library includes a fix for the accumulator operations where it would fail on 32 bit systems.
> main: update utreexo library

- blockchain/internal/sizehelper/sizehelper.go
- blockchain/internal/sizehelper/sizehelper_test.go
- blockchain/utreexoio.go
- blockchain/utreexoio_test.go
- blockchain/utxocache.go
- blockchain/utxocache_test.go
- blockchain/utxoviewpoint.go
This is done so that some of the code in package blockchain can be separated out into other packages to better guarntees that there isn't unexported code that is being accessed by a function that shouldn't be accessing it.
> blockchain, sizehelper: move sizehelper to separate package

- chaincfg/params.go
Extra dnsseeds from calvin kim are added as well as correctly stating that the existing seeds from calvin kim support filtering.
> chaincfg: update dnsseeds

- blockchain/internal/sizehelper/sizehelper.go
- blockchain/internal/sizehelper/sizehelper_test.go
- blockchain/utreexoio.go
- blockchain/utreexoio_test.go
The test code for CalcNumEntries is moved and is made better by adding
more test cases for it. This catches the bug where the current code
isn't accurate to 1% of the requested maxSize.
CalcNumEntries wasn't so accurate as it was leaving some room that
could've been utilized. The code is changed to check for more sizes
and is now accurate up to 0.1% of the requested maxSize.
> sizehelper, blockchain: move CalcNumEntries code to sizehelper package and fix bugs

- blockchain/indexers/flatutreexoproofindex.go
Since pruned nodes do not keep the historical proofs, attempting to prune them results in a runtime panic.
> indexers: don't prune proofs if the node is pruned

- netsync/manager.go
When a tx inv was given, we may get stuck as it interferes with the headers building. Ignoring all invs when we're in headers build avoids this problem.
> netsync: ignore invs when we're in headers build mode

- connmgr/seed.go
Utreexo nodes need to be connected to other utreexo nodes to get txs and blocks. Ignore the seeds that do not support filtering as they gives nodes that don't provide the required data.
> connmgr: ignore dnsseeds that don't support filetering for utreexo nodes

- btcjson/chainsvrcmds.go
- btcjson/chainsvrresults.go
- cmd/utreexoctl/version.go
- rpcserver.go
- rpcserverhelp.go
The getbeststate rpc mainly helps with setting new assumeutreexo points
as the beststate information is necessary for setting them.
> btcjson, main, utreexoctl: add getbeststate command

- blockchain/utreexoviewpoint.go
- wire/leaf.go
Doing this allows pretty printing because for %v go will call String() instead of printing out a byte slice.
> blockchain, wire: rename ToString() to String()

- electrum/server.go
Some clients will send batched rpc requests. To handle this, we assume
every request is a batched rpc request and fall back to unmarshalling as
a single request when it errors.
> electrum: handle batch rpc requests

- wallet/watchonly.go
When the mempool didn't have caching built in, it used to have the full udata attached to the tx. But since this is not the case anymore, watchonly wallet panics as it tries to access something that no longer exists.
We change the code to fetch the leafdatas from the mempool directly as it can now be fetched from there.
> wallet: fix how leafdatas are fetched

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/utreexobackend.go
- blockchain/indexers/utreexoproofindex.go
- blockchain/indexers/utreexoproofstats.go
- server.go
- wire/leaf.go
- wire/leaf_test.go
- wire/msgblock.go
- wire/msgtx.go
- wire/udata.go
- wire/udata_test.go
The unconfirmed marker created a discrepancy between the proof sent out
for blocks and transactions. It was used for marking if a referenced tx
that was being spent was unconfirmed or not but it's removed in favor of
the node checking locally for the referenced tx. If the node is unable
to find all the referenced txs, the tx is put into the orphan pool.
> wire, main, indexers: remove unconfirmed marker

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/utreexoproofindex.go
GetLeafPosition returns the position and a boolean indicating whether or not a hash was found. The boolean wasn't being checked which ended up with the hashes that weren't found where being included as a 0.
We omit the positions entirely in this commit if they were not found.
> indexers: only include positions that were found

- blockchain/internal/utreexobackends/cachedleavesmap.go
- blockchain/internal/utreexobackends/nodesmap.go
- blockchain/utreexoio.go
Address issue https://github.com/utreexo/utreexod/issues/195
> Remove heap allocations when flushing the nodes or cached leaves

- blockchain/chain.go
- blockchain/indexers/addrindex.go
- blockchain/indexers/cfindex.go
- blockchain/indexers/common.go
- blockchain/indexers/flatfile.go
- blockchain/indexers/flatfile_test.go
- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- blockchain/indexers/manager.go
- blockchain/indexers/ttlindex.go
- blockchain/indexers/txindex.go
- blockchain/indexers/utreexobackend.go
- blockchain/indexers/utreexobackend_test.go
- blockchain/indexers/utreexoproofindex.go
- blockchain/internal/utreexobackends/cachedleavesmap.go
- blockchain/internal/utreexobackends/cachedleavesmap_test.go
- blockchain/internal/utreexobackends/nodesmap.go
- blockchain/internal/utreexobackends/nodesmap_test.go
- blockchain/utreexoio.go
- blockchain/utreexoio_test.go
- blockchain/utxocache.go
- config.go
- database/ffldb/db.go
- database/interface.go
- netsync/manager.go
- server.go
When running either the `utreexoproofindex` or the `flatutreexoproofindex` they will not be able to recover in cases of unexpected shutdown. This forces the user to reindex which is very costly.
The changes here make it so that the utreexo proof indexes are able to recover even in cases of unexpected shutdowns.
> Make bridge nodes recoverable

- version.go
Backwards incompatible P2P changes and the change to make recoverable bridge node possible are enough to require a minor version bump.
> main: bump version to 0.4.0

- blockchain/utxocache.go
- blockchain/utxocache_test.go
- wire/msgblock.go
Same bug fix as https://github.com/btcsuite/btcd/pull/2122
> wire, blockchain: don't use blockheightbyhash for height fetching

- blockchain/chain.go
- blockchain/utreexoviewpoint.go
- blockchain/validate.go
The accumulator verification and modification was being done in a single function. This meant that if the accumulator verification passed while signature validation failed, the node would be left at an inconsistent state. The change here prevents that from being possible.
> blockchain: refactor code to separate out accumulator verification and modification

- .github/workflows/go.yml
- blockchain/utreexoviewpoint.go
- btcjson/help.go
- go.mod
- go.sum
- goclean.sh
- wire/batchproof.go
- wire/batchproof_test.go
- wire/udata.go
We update the utreexo lib and change some functions to account for the change in the library.
> main, wire: update utreexo lib

- wire/leaf.go
- wire/leaf_test.go
- wire/message.go
- wire/message_test.go
- wire/msgutreexotx.go
- wire/udata.go
- wire/udata_test.go
Utreexo tx is a transaction message with utreexo proof attached.
Favoring this over the current method which is to have a separate
utreexo encoding for the transaction message.
> wire: add msgutreexotx

- btcutil/utreexotx.go
UtreexoTx is a wrapper around MsgUtreexoTx and adds helpful method just like Tx adds helpful methods for MsgTx.
> btcutil: add utreexotx

- mempool/mempool.go
Since the leaves are the actual data we need, it's better that the function argument is the leaves and not the udata. This allows for calling fetchInputUtxosFromLeaves from a different mempool method as the leaves are kept track of.
> mempool: refactor fetchInputUtxosFromUData to fetchInputUtxosFromLeaves

- mempool/mempool.go
checkmempoolacceptance takes in udata and internally uses it for tx verification if it's not nil. This change is made to support utreexotx messages.
> mempool: take in utreexo data as an argument for checkMempoolAcceptance

- wire/udata.go
Done for equality so that reflect.DeepEqual() returns true. If we allocate then it's not equal.
> wire: don't allocate if udata count is 0

- electrum/server.go
- mempool/interface.go
- mempool/mempool.go
- mempool/mempool_test.go
- mempool/mocks.go
- netsync/manager.go
- peer/peer.go
- rpcserver.go
- server.go
- wire/msgblock.go
- wire/msgtx.go
We favor utreexotx instead of having a separate utreexo encoding for a transaction message.
The code here changes the code so that CSNs ask for utreexotxs and the CSNs and bridges
send over utreexotxs.
> mempool, netsync, electrum, main, peer: Use utreexotx

- netsync/manager.go
When we're all caught up and we have a new peer, we'll ask for blocks from peers that we're on the same height. Since these peers don't have any blocks to send us, they don't reply and we disconnect from them as they timeout.
To prevent this, we don't ask for blocks if the chain thinks we're current and do not have a peer that reports having a higher block.
> netsync: don't ask for blocks from peers on the same block height

- netsync/manager.go
- server.go
- wire/leaf.go
- wire/message_test.go
- wire/msgutreexotx.go
Biggest change made here is to do `PreviousOutPoint.Index <<= 1` and use the LSB to indicate if the
TxIn is confirmed or not. This is mainly done to give ordering to the LeafDatas and the TxIns. Without
this, it's hard to tell which LeafData is for which TxIn.
> wire, netsync: change MsgUtreexoTx serialization

- electrum/server.go
- netsync/manager.go
- server.go
- wallet/watchonly.go
- wire/msgtx.go
- wire/msgutreexotx.go
Since we're using MsgUtreexoTx, we have no need for the UData field in MsgTx.
> wire, electrum, netsync, wallet, main: remove udata from MsgTx

- peer/peer.go
For each message that wasn't successfully read, there will now be a debug message indicating which peer and what error it was.
> peer: add debug message for readMessage

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/utreexoproofindex.go
- blockchain/utreexoviewpoint.go
- mempool/mempool.go
- mempool/mempool_test.go
- server.go
- wire/leaf.go
- wire/msgutreexotx.go
Biggest changes:
1: MsgUtreexoTx now includes the LeafDatas and the Proof directly instead of having UData as a field.
2: Each TxIn's OutPoint.Index now also encodes if the OutPoint being addressed is confirmed or not.
3: The count of the LeafData is no longer written. The count is implied by the len(TxIn) and if each LeafData is confirmed or not.
4: Various code changes to account for the fact that there's LeafDatas that are for unconfirmed TxIns exist within the slice of LeafDatas.
> blockchain, main, wire, indexers: change MsgUtreexoTx serialization

- rpcserverhelp.go
- server.go
TxTotals were only updating for the bridge nodes and it was generating proofs on the fly to calculate the size. Now the totals are kept track with CSNs and the size of the received MsgUtreexoTx is recorded.
> main: fix txtotals count

- netsync/manager.go
We'll still ask for txs from our peers on tx invs even during ibd. This is meaningless since the txs will just go straight to the orphan pool anyways.
> netsync: ignore tx invs if not caught up

- server.go
Requiring node network on peers prevent CSNs from connecting to each other. While you can't sync off of a pruned CSN during ibd, you are able to receive txs from them so it's better to not require node network on peers.
> main: don't require node network

- blockchain/utreexoviewpoint.go
- go.mod
- go.sum
Updated to the new utreexo library with the bug fix and also fixed the bug where we attempt to hash unconfirmed leafdatas.
> main, blockchain: fix bug for csns serving txs to other csns

- chaincfg/params.go
Mainly done so that the new utreexo header download mode doesn't hold too much headers in memory
> chaincfg: add checkpoints for signet

- netsync/manager.go
- peer/peer.go
- server.go
- wire/message.go
- wire/msggetutreexoheader.go
- wire/msgutreexoheader.go
We introduce MsgUtreexoHeader and GetMsgUtreexoHeader messages that's used to communicate the positions of the leaves in the utreexo accumulator that are being spent in a given block.
> wire, main, peer, netsync: utreexo header messages

- .github/workflows/go.yml
- blockchain/utreexoviewpoint.go
- rust-toolchain.toml
It's not used in ExtractAccumulatorAdds so we're removing it.
> blockchain: remove udata requirement from ExtractAccumulatorAdds

- wire/message.go
- wire/msggetutreexoproof.go
- wire/msgutreexoproof.go
Instead of a msgutreexoblock, we prefer having a separate msgblock and a
msgutreexoproof. This separates out the utreexo data from the msgblock
which allows having a utreexo bridge node which can opt to not save the
blocks.
MsgGetUtreexoProof allows nodes to request for specific data in a
utreexo proof. This lets nodes to omit requesting for hashes that it's
caching and thus allows for bandwidth savings.
> wire: add msgutreexoproof and msggetutreexoproof

- server.go
We were putting in the length of leafdatas for numadds instead of the leaves that we were adding into the accumulator.
We fix the bug and refactor the function for readability.
> main: fix bug in getutreexoheader handling code

- blockchain/blockindex.go
Since ProcessBlockHeader will add the block header as a blockNode to the blockIndex, the HaveBlock function will incorrectly state that the block exists when only the header exists.
Because of this, we check that the node exists and also check the node's status to see if the data is stored.
> blockchain: change HaveBlock behavior

- blockchain/accept.go
- netsync/manager.go
maybeAcceptBlockHeader verified the passed in block header and set it as the best tip on it passing verification. However, since the best tip is used for marking a block that's passed all verification and headers verification isn't complete verification, we remove the code for adding the blockNode as the best tip.
This allows us to use the ProcessBlockHeader code for verification of a header without accepting it as well.
> blockchain: don't assign header as the best tip on maybeAcceptBlockHeader

- blockchain/process_test.go
The added test ensures that headers validate if there exists a header that is the parent of the first block header in the slice of headers. Fails if there is not.
> blockchain: add test for ProcessBlockHeader

- netsync/manager.go
- server.go
We change the code to handle headers and request headers from peers for
new block messages. This allows utreexo nodes to use the same code for
syncing up during ibd for new blocks as well.
> netsync, main: always download headers for blocks

- netsync/manager.go
On fetchHeaderBlocks and fetchUtreexoHeaders, we make sure that both the syncPeer and the passed in peer are not nil. We also only prefer the passed in peer if it is not nil.
> netsync: fix bug in peer selection logic

- netsync/manager.go
Instead of stating that the header failed to connect, state that the header failed header validation.
> netsync: make log more specific

- netsync/manager.go
- peer/peer.go
- server.go
The utreexo proofs are no longer included in the block message. Instead, they're
separated out into their own message so the SyncManager needs to handle requesting
and handling both the block and the utreexo proof message.
In the changes made here, we keep track of the numLeaves from the utreexoHeaders and
we hold onto them as they're needed when constructing the GetUtreexoProof message.
Then we request the GetUtreexoProof message and request them while fetching the blocks
and add them to the blocks while processing the block messages.
> netsync, main: use utreexo proof message to validate blocks

- blockchain/accept.go
- blockchain/chain.go
- blockchain/chainio.go
- blockchain/fullblocktests/common_test.go
- blockchain/process.go
- blockchain/process_test.go
- netsync/manager.go
Since we now accept headers for new block announcements, it's impossible to distinguish between
new block announcements and headers received from ibd in the same code block.
We change the code to rely on `ProcessBlockHeader` for block header connection and for figuring out
best chain selection instead of a strict "does this blockheader connect to the previous one".
This avoids errors that happens during ibd where a block header is rejected and a peer is banned because
of new header announcements that fail to connect as the node does not have the entire chain of headers yet.
> blockchain, netsync: no more headers-first list

- blockchain/indexers/flatutreexoproofindex.go
Root summaries are the utreexo accumulator of each of the roots at each block.
The roots at each block are hashed and they become the leaves of this accumulator.
This allows for committing the root summary into the binary so that peers may be able
to serve the proof and the roots at a given block.
The root summaries are generated every 50,000 blocks and the proofs are backwards
compatible as no leaves are removed from the accumulator. The new proofs will just have
extra hashes appended to the end which the requesting node can safely ignore.
> blockchain, indexers: generate root summaries

- wire/message.go
- wire/msggetutreexoroot.go
- wire/msggetutreexoroot_test.go
MsgGetUtreexoRoot can be used to ask peers to send the utreexo roots and the proof for it.
> wire: add MsgGetUtreexoRoot

- wire/message.go
- wire/msgutreexoroot.go
MsgUtreexoRoot is a response to the MsgGetUtreexoRoot message and
includes information about the utreexo roots at a given block as well as
the proof for it.
> wire: add MsgUtreexoRoot

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- blockchain/indexers/utreexobackend.go
- blockchain/indexers/utreexoproofindex.go
- rpcserver.go
The utreexo root was saved before the modification with the justification that it was easier for reorgs. This mistake is now corrected.
> indexers, main: fix off by one root error

- blockchain/indexers/flatutreexoproofindex.go
Since all the roots are now saved on disk, we shouldn't be fetching the current state to be saved on disk as that will be a duplicate.
> indexers: don't add the current state

- peer/peer.go
- server.go
MsgGetUtreexoRoot is now handled and we'll serve out utreexoroot messages to peers.
> peer, main: add handling code for getutreexoroot

- netsync/manager.go
- wire/msggetutreexoheader.go
- wire/msggetutreexoheader_test.go
Since utreexoheader includes proofs that could be beyond the what the ibd-ing node has the roots for, it's good to have a method to omit what's not necessary. The bool here allows the requester to do just that.
> wire, netsync: add includeproof bool to getutreexoheader

- netsync/manager.go
- server.go
- wire/msgutreexoheader.go
- wire/msgutreexoheader_test.go
The proof hashes prove that the utreexoheader was included in the accumulator hashes that were committed in the binary.
> wire: add proof hashes to msgutreexoheader

- netsync/manager.go
Since this value is subject to change, basing on this value may cause inconsistencies during ibd. Better to base off of the best header height which is local.
> netsync: don't sync based on peer's last block

- netsync/manager.go
There's no need to fetch the block header and we should always print the log regardless of whether or not we're in headers first mode.
> netsync: simplify logging in fetchheaders

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- blockchain/indexers/utreexoproofindex.go
The utreexo indexers now keep track of the block summaries in an accumulator state
and is now able to generate proofs for them as well.
> indexers: add block summary state to the utreexo indexers

- netsync/manager.go
- server.go
- wire/msggetutreexosummaries.go
- wire/msggetutreexosummaries_test.go
We change the getutreexosummaries message to support requests for multiple block
summaries at once.
> wire: req multiple summaries

- wire/msggetutreexosummaries.go
- wire/msggetutreexosummaries_test.go
- wire/msgutreexoblocksummaries.go
We change the getutreexosummaries message to only allow for blocks in powers of 2 by changing the maxblocks to exponent.
> wire: change maxgetblocks to exponent

- netsync/manager.go
- server.go
Since the getutreexosummaries allows us to fetch for multiple summaries at
a time, we change the code to take advantage of this as well as to handle it
if we're a node serving the utreexo summaries.
> main, netsync handle multiple summaries

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/utreexoproofindex.go
- btcjson/chainsvrcmds.go
- btcjson/chainsvrresults.go
- rpcserver.go
- rpcserverhelp.go
`getutreexosummaryroots` call is added so that we'll be able to easily update the
committed block summary roots in the binary.
> indexers, btcjson, main: add rpcserver commands for blocksummarysstate

- chaincfg/params.go
- netsync/manager.go
- server.go
- wire/msggetutreexosummaries.go
- wire/msggetutreexosummaries_test.go
We now verify the proof in the blocksummary against the pre-committed
block summary accumulator. This prevents malicious peers to spam block summaries
during ibd.
> chaincfg, wire, main, netsync: verify the proof in the blocksummary

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- blockchain/indexers/utreexoproofindex.go
- netsync/manager.go
- server.go
- wire/msggetutreexosummaries.go
- wire/msggetutreexosummaries_test.go
includeproof boolean is added to getutreexoblocksummaries and it allows for requesters
to receive the proof with the utreexoblocksummaries or not.
> wire, indexers, netsync, main: add includeproof bool to getblocksummaries

- blockchain/accept.go
- blockchain/chainio.go
The bestHeader chainview would not be set up correctly which led to a node that has not finished ibd-ing to download headers on each startup.
Flushing the index per header and initializing the bestheader correctly alleviates this bug.
> blockchain: fix bug in setting the bestHeader chainView

- netsync/manager.go
The headersFirstMode and startHeader wasn't set for when a node needed to download block summaries.
> netsync: correctly set headersFirstMode and startHeader

- blockchain/accept.go
2 things:
1. When processing headers that already exist, it'll now correctly return the isMainChain boolean instead of always returning false.
2. If the header to be processed doesn't exist in the bestHeaders but it does exist in the blockindex, that header will be processed again.
> blockchain: verify blockheader if it's not included in bestHeaders

- server.go
- wire/msggetutreexoproof.go
- wire/msggetutreexoproof_test.go
For requesting proof positions and leafdata positions, we now request them using a bitmap instead of uint64 positions. This makes requests more data efficient.
> wire, main: change getutreexoproof message to use bitmaps

- blockchain/chainio_test.go
- blockchain/indexers/utreexobackend.go
- blockchain/internal/utreexobackends/cachedleavesmap.go
- blockchain/utreexoio.go
- blockchain/utreexoio_test.go
- go.mod
- go.sum
Utreexo library on v0.5.0 introduces `LeafInfo` on the CachedLeaves.
The `LeafInfo` stores the created height and the index, which allows
quick lookup of where the deleted leaf was originally created. This allows
for generating the TTL values for the block summaries on each of the deleted
leaves.
> blockchain, utreexobackends, main, indexers: update to utreexo lib v0.5.0

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- blockchain/indexers/utreexobackend.go
- blockchain/indexers/utreexoproofindex.go
The ttls for each block are required for blocksummaries. We now keep track of them
in the pollard state and write them to the flat files as the leaves are spent.
> indexers: write ttls for flatutreexoproofindex

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
If they go over the maxuint16 value, we simply don't mark their actual ttls. This is on the basis that most utxos have a low ttl and a cache value that includes the ones that go over the maxuint16 value just might as well cache everything.
> indexers: change ttls to uint16

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- blockchain/indexers/utreexoproofindex.go
- netsync/manager.go
- server.go
- wire/msggetutreexosummaries.go
- wire/msggetutreexosummaries_test.go
- wire/msgutreexoblocksummaries.go
The summaries will no longer be used for ibd optimizations so they don't need to be committed.
> wire, main, indexers, netsync: remove proofhashes from msgutreexoblocksummaries

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/utreexoproofindex.go
- netsync/manager.go
- wire/utreexoblocksummary.go
We change numAdds to uint64 and use varint serialization as you can have a block with more than math.MaxUint16 utxos.
> wire, blockchain, netsync: change numAdds to uint64

- wire/message.go
- wire/msgutreexottls.go
- wire/msgutreexottls_test.go
- wire/utreexottls.go
The msgttls provide ttls for each of the blocks, allowing for caching optimizations by the nodes during ibd.
> wire: add msgttls

- wire/msggetutreexoproof.go
- wire/msgutreexoproof.go
- wire/msgutreexoproof_test.go
The targets allow the nodes to request for full proof information when
asking for the utreexo proof.
> wire: add targets to msgutreexproof

- netsync/manager.go
- server.go
- wire/msggetutreexoproof.go
We no longer do block summary based downloads as they aren't
used for caching proof during ibd anymore.
We also change the proof serving code to serve everything if the
target bool is true in the getutreexoproof message.
> netsync, wire, main: don't download summaries

- blockchain/indexers/flatutreexoproofindex.go
- wire/batchproof.go
- wire/udata.go
At the moment we clump all three (targets, proof hashes, and leafdata) into
a single udata chunk. This forces us to fetch all of them when serving the
utreexo proof to a peer.
Since the peer is able to ask for a subset of any of the three so we modify the
flatutreexoproofindex so that they're able to be independently fetched.
> indexers, wire: separate out targets, proof, and leafdata in flatutreexoproofindex

- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- wire/msgutreexottls_test.go
- wire/utreexottls.go
We make this change as the protocol won't serve targets in the ttl messages as the ttls imply the targets in the future.
> wire, indexers: change ttls back to uint64

- netsync/manager.go
- wire/msggetutreexosummaries.go
- wire/msggetutreexottls.go
The function checks that the given message verifies against the utreexo
stump in the binary and accepts the ttl into the map.
> wire, netsync: add handle utreexo ttl msg

- blockchain/utreexoviewpoint.go
Since caching is only relevant for additions, we remove the unnecessary argument in ExtractAccumulatorDels.
> blockchain: remove unnecessary remembers in ExtractAccumulatorDels

- netsync/manager.go
With the ttls, we keep track of their deathheights, allowing us to calculate the
targets at a given future height. These generated targets will be used to calculate
which proof hashes we need to download in the future.
> netsync: calc targets from ttls

- blockchain/chain.go
- blockchain/indexers/flatutreexoproofindex.go
- blockchain/indexers/indexers_test.go
- blockchain/indexers/utreexobackend.go
- blockchain/indexers/utreexoproofindex.go
- blockchain/utreexoviewpoint.go
We add `leafCache` to `UtreexoViewpoint` and cache the leaves if we the
ttls are available in the given block. The algorithm used to cache the leaves
is the clairvoyant algorithm.
For now, we set the cached leaf count to 4000. This is bound to be adjustable
in the future.
> blockchain, indexers: add clairvoyant caching
