blockchain/indexers/indexers_test.go
Refactors the test code to remove duplicates and make them into separate
functions.  Helps with readability and maintainability of the code.
=> indexers/indexers_test: Refactor indexers_test

blockchain/indexers/indexers_test.go
Utreexo proof that was generated by the proof indexes are tested per
block on the indexer that generated it.  This tests the underlying
forest accumulator type.
=> indexers/indexers_test: Test utreexo proof per block

blockchain/utreexoviewpoint.go, go.mod, go.sum
New features have been added to the utreexo library.  Update the library
to use those features.
=> go.mod: Update utreexo library

blockchain/accept.go, blockchain/blockindex.go, blockchain/chain.go, blockchain/chain_test.go, blockchain/common.go, blockchain/error.go, blockchain/fullblocks_test.go, blockchain/fullblocktests/common_test.go, blockchain/fullblocktests/generate.go, blockchain/fullblocktests/process_test.go, blockchain/notifications_test.go, blockchain/process.go, blockchain/utxocache_test.go, blockchain/validate_test.go
Added the functions that would be required for header validation at the time of header download. The changes to existing functions are commented until these functions are incorporated completely so that the functioning is not affected.
=> Header validation

blockchain/chain.go
Utreexo compact state nodes would try to flush the utxo cache during a reorg, resulting in a segfault. Code is changed so that a utreeox compact state node does not try to flush the utxo cache.
=> blockchain: Fix CSN reorg bug

blockchain/chain.go, blockchain/chain_test.go, blockchain/common.go
ReconsiderBlock is added to BlockChain and it enables the ability to reconsider invalid blocks and the branch that the invalid block is included in. This is useful for undoing the effects of invalidateBlock.
=> blockchain: Add ReconsiderBlock

blockchain/chain.go
reorganizeChain wasn't properly handling the reconstruction of utreexo data and the generation of update data/utreexo adds for the wallet. The bugs fixed here address:
1: Proper block hashes that are commited in the leaves are properly
fetched.
2: The data that is needed for wallets (update data/utreexo adds) are
properly generated.
=> blockchain: Fix reorg bugs with utreexo csn

blockchain/chain.go, blockchain/utreexoviewpoint.go, blockchain/validate.go, wallet/watchonly.go
Some returned errors now have better description of what the error was.
=> blockchain, wallet: Better error messages

integration/utreexocompactstatenode_test.go
genSpend in the integration test may sometimes try to spend immature outputs because of the hardcoded 25btc spend.  Lower the hardcoded amount to 20 and make it ok to fail when trying to spend as that doesn't really affect the overall test.
=> integration: Handle when genSpend tries to spend immature outputs

blockchain/chain.go, config.go, database/ffldb/blockio.go, database/ffldb/db.go, database/ffldb/driver_test.go, database/interface.go
Fixes a couple of bugs, adds new test.
=> database, main, blockchain: improve pruning code

blockchain/chain.go, blockchain/validate.go
In checkConnectBlock, a separate utreexo view is asked to be passed in. This is to avoid mutation of the utreexo view that's part of the blockchain struct as some callers may want to pass in another utreexoview during events such as reorgs.
=> blockchain: ask for a utreexoview in checkConnectBlock

.github/workflows/go.yml, goclean.sh
The expensive coverage generation is now removed from the tests.
=> main: change goclean

blockchain/indexers/indexers_test.go
The utreexo csn wasn't being fed enough blocks to cause a reorg and the reorg code wasn't being tested for csns.  Some changes to the multi-block proofs were also made as it's not possible to sync to the tip of where the bridge is with only multiblock proofs.
=> blockchain/indexers: fix utreexo index test

blockchain/chain.go
2 bugs are fixed in this PR.
1: Before attempting to prune the index, make sure the index exists. 2: Before attempting to calculate if the flush is needed for the utxo
cache, check that the utxo cache is present.
=> blockchain: Fix prune bug

server.go
Fixes a bug where a csn would crash upon serving a tx to a peer.
=> main: fix csn serve tx bug

blockchain/indexers/flatutreexoproofindex.go, blockchain/indexers/utreexoproofindex.go
The added GetLeafHashPsositions and GenerateUDataPartial are needed to serve partial utreexo proofs to utreexo nodes.
=> indexers: add methods for partial proof tx propagation

btcutil/address.go, btcutil/address_test.go, btcutil/internal_test.go
Adding the taproot address type. Needed to support taproot in utreexod.
=> address: add AddressTaproot

blockchain/chain.go, blockchain/common.go, blockchain/thresholdstate.go, blockchain/thresholdstate_test.go, blockchain/versionbits.go, btcjson/chainsvrresults.go, chaincfg/deployment_time_frame.go, chaincfg/params.go, integration/bip0009_test.go, rpcserver.go
Working towards taproot support. Taken from btcd
=> chaincfg+blockchain: abstract/refactor BIP 9 version bits implementation to work w/ BIP 8 block heights

version.go
Since this is gonna be the first utreexod release, it should be 0.1.0
=> main: update version to 0.1.0

config.go, integration/getutreexoroots_test.go, integration/invalidate_reconsider_block_test.go, integration/utreexocompactstatenode_test.go
Unless given the --prune=0 flag, the node will default to --prune=550
=> main, integration: making pruning the default

addrmgr/addrmanager_internal_test.go
Sometimes the tests in the addrmanager_internal_test will fail with: "addrmanager_internal_test.go:124: expected to find 5 addresses, found 4"
This is because the generated address with randAddr() may not always generate an address that's routable. If the address is not routable, that address will not be added to the manager when calling AddAddress().
This bug is fixed by creating a new function routableRandAddr() that always creates a routable random address.
=> addrmgr: fix intermittent addrmanager_internal_test bug

blockchain/sizehelper.go
Upstream fix from github.com/btcsuite/btcd
commit 7644d14078db276c31ab8f304e5edbbfd2699e4c
=> blockchain: fix build for 32-bit build system

blockchain/indexers/indexers_test.go
Helps with reproducing the bug on errors.
=> indexers: print time used for generating rand for index tests

server.go
A csn would previously connect to any node that signaled NODE_NETWORK. However, since a csn can't sync or verify txs from such nodes, it's not feasible to have them as peers to receive txs or blocks from.
However, it's possible to give txs/blocks to these peers. But we'll get to that at a later time.
=> main: don't connect to non-utreexo peers as a csn

version.go
New rpcs added so bumping version to 0.3.0
=> main: bump version to 0.3.0

README.md
Corrects the disclaimer that currently discourages non-negligible amounts, and changes the currency name to lowercase.
=> Fix README disclaimer

netsync/manager.go
2 things are changed:
1: We allow checkHeadersList to remove from the headerList even if the
SyncManager is not in headers-first mode as we're now receiving
headers for new block annoucements.
2: We remove headers when we no longer have checkpoints as the main
reason we keep the last headerNode is to check that the next
checkpoint connects.
This is not needed on headers-first with no checkpoints as we don't
perform that check.
This is also not needed on new block annoucements as we will have the
chain tip.
=> netsync: change checkHeadersList behavior

wire/msggetutreexoproof.go
ConstructGetUtreexoProofMsg is a convinence function to construct a GetUtreexoProofMsg with the given inputs. It will always include every proof hash and target that's needed with the given inputs.
=> wire: add ConstructGetUtreexoProofMsg

blockchain/indexers/flatutreexoproofindex.go, blockchain/indexers/utreexobackend.go, blockchain/indexers/utreexoproofindex.go, config.go
The code doesn't support having 0 or less than 0 for the utreexo proofindex cache so enforce that in the flag.
=> main: put a minimum of 250mib for utreexoproofmaxmemory

blockchain/indexers/flatutreexoproofindex.go
FetchMsgUtreexoRoot can be used by callers to fetch a constructed MsgUtreexoRoot to serve to peers.
=> indexers: add FetchMsgUtreexoRoot

blockchain/indexers/indexers_test.go, blockchain/indexers/utreexoproofindex.go, server.go
Make utreexoproofindex feature compatible with flatutreexoproofindex and add the utreexoRootsState.
=> indexers: add utreexoRootsState to utreexoproofindex

netsync/manager.go
Series of bugs are fixed:
1: checks that the blocksummary exists in the cache before operating
with it.
2: checks that we have requested for the block summary before operating
with it.
3: checks that the block summary isn't empty before operating with it.
=> netsync: check that the block summary is good before operating on it

wallet/watchonly.go
Hi! I fixed a broken link in the `watchonly.go` file.
=> fix: dead link in `watchonly.go`

netsync/manager.go
We weren't checking it see if some blocks were requested from specific peers for fetch block headers. Checking prevents asking for blocks that we've already have in the request queue.
=> netsync: fix unrequested block bug

txscript/standard.go, upnp.go, utreexod.go
make function comment match function name
=> chore: make function comment match function name

wire/msgfilterclear_test.go, wire/msgfilterload_test.go, wire/msgtx_test.go
fix some function names in comment
=> chore: fix some function names in comment

blockchain/indexers/flatutreexoproofindex.go, btcjson/chainsvrcmds.go, btcjson/chainsvrresults.go, chaincfg/params.go, netsync/manager.go, rpcserver.go, rpcserverhelp.go
ttl accumulator is added so that the ttls can be proven against an accumulator.
=> indexers: add ttl accumulator

chaincfg/params.go
We update the ttl states for signet and mainnet.
=> chaincfg: update committed utreexo ttl state

blockchain/chain.go, blockchain/utreexoviewpoint.go, netsync/manager.go
The changes to headers-first download is now addressed with the assumeUtreexo mode.
=> netsync, blockchain: fix assume utreexo
